### ISSUE TITLE
Options is not used until node-jsx is required.

### ISSUE THREAD

**Issue by jontelm** [petehunt/node-jsx#33]
If node-jsx is required after example Express, all express files will be checked by node-jsx but without options. So require node-jsx before express, otherwise will it take some extra time to start node / express.

Wrong:
```javascript
var express = require('express'), // node-jsx options is empty here
    fs = require('fs'), // node-jsx options is empty here
    passport = require('passport'), // node-jsx options is empty here
    nodeJSX = require('node-jsx').install({extension: '.jsx'}); // It's here the options starts to take action and only jsx will be checked.
```
Right:
```javascript
var nodeJSX = require('node-jsx').install({extension: '.jsx'}),
    express = require('express'),
    fs = require('fs'),
    passport = require('passport');
```

Not a big deal, but maybe something we should add to the readme ?

**Comment by mweitzel** [comment]
Things like `require` and load order are pretty fundamental to node, but not this library. I think it'd be a little out of place to include in this readme.

**Comment by jontelm** [comment]
Yes, I agree. This issue can maybe help someone later on.
